/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const PlayerId = IDL.Principal;
export const GameState = IDL.Record({
  'id' : IDL.Nat,
  'isGameStarted' : IDL.Bool,
  'lastUpdate' : Time,
  'players' : IDL.Vec(PlayerId),
});
export const LobbyState = IDL.Record({
  'id' : IDL.Nat,
  'owner' : PlayerId,
  'players' : IDL.Vec(PlayerId),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'gamesPlayed' : IDL.Nat,
  'wins' : IDL.Nat,
});
export const Position = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'z' : IDL.Float64,
  'rotation' : IDL.Float64,
});
export const PlayerState = IDL.Record({
  'username' : IDL.Text,
  'lastUpdated' : Time,
  'isAlive' : IDL.Bool,
  'position' : Position,
  'health' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'endGame' : IDL.Func([IDL.Nat], [GameState], []),
  'getActiveLobbies' : IDL.Func([], [IDL.Vec(LobbyState)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlayersInGame' : IDL.Func([], [IDL.Vec(PlayerState)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinLobby' : IDL.Func([], [LobbyState], []),
  'leaveLobby' : IDL.Func([IDL.Nat], [LobbyState], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startGame' : IDL.Func([IDL.Vec(PlayerId)], [GameState], []),
  'updatePlayerPosition' : IDL.Func([Position], [IDL.Vec(PlayerState)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const PlayerId = IDL.Principal;
  const GameState = IDL.Record({
    'id' : IDL.Nat,
    'isGameStarted' : IDL.Bool,
    'lastUpdate' : Time,
    'players' : IDL.Vec(PlayerId),
  });
  const LobbyState = IDL.Record({
    'id' : IDL.Nat,
    'owner' : PlayerId,
    'players' : IDL.Vec(PlayerId),
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'gamesPlayed' : IDL.Nat,
    'wins' : IDL.Nat,
  });
  const Position = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'z' : IDL.Float64,
    'rotation' : IDL.Float64,
  });
  const PlayerState = IDL.Record({
    'username' : IDL.Text,
    'lastUpdated' : Time,
    'isAlive' : IDL.Bool,
    'position' : Position,
    'health' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'endGame' : IDL.Func([IDL.Nat], [GameState], []),
    'getActiveLobbies' : IDL.Func([], [IDL.Vec(LobbyState)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlayersInGame' : IDL.Func([], [IDL.Vec(PlayerState)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinLobby' : IDL.Func([], [LobbyState], []),
    'leaveLobby' : IDL.Func([IDL.Nat], [LobbyState], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startGame' : IDL.Func([IDL.Vec(PlayerId)], [GameState], []),
    'updatePlayerPosition' : IDL.Func([Position], [IDL.Vec(PlayerState)], []),
  });
};

export const init = ({ IDL }) => { return []; };