/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type GameMap = { 'jungle' : null } |
  { 'city' : null } |
  { 'desert' : null } |
  { 'island' : null };
export interface GameState {
  'id' : bigint,
  'isGameStarted' : boolean,
  'lastUpdate' : Time,
  'players' : Array<PlayerId>,
}
export interface LobbyState {
  'id' : bigint,
  'selectedMap' : GameMap,
  'owner' : PlayerId,
  'players' : Array<PlayerId>,
}
export interface MatchState {
  'id' : bigint,
  'map' : GameMap,
  'startTime' : Time,
  'isActive' : boolean,
  'players' : Array<PlayerId>,
}
export type PlayerId = Principal;
export interface PlayerState {
  'username' : string,
  'lastUpdated' : Time,
  'isAlive' : boolean,
  'position' : Position,
  'health' : bigint,
}
export interface Position {
  'x' : number,
  'y' : number,
  'z' : number,
  'rotation' : number,
}
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'gamesPlayed' : bigint,
  'wins' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'endGame' : ActorMethod<[bigint], GameState>,
  'getActiveLobbies' : ActorMethod<[], Array<LobbyState>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlayersInGame' : ActorMethod<[], Array<PlayerState>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinLobby' : ActorMethod<[], LobbyState>,
  'leaveLobby' : ActorMethod<[bigint], LobbyState>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selectMap' : ActorMethod<[bigint, GameMap], undefined>,
  'startGame' : ActorMethod<[bigint], MatchState>,
  'updatePlayerPosition' : ActorMethod<[Position], Array<PlayerState>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];